{% set name = "ape" %}
{% set version = "2.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/fermi-lat/ape
  git_rev: standalone
build:
  number: 1

requirements:
  build:
   - cmake >=3.12
   - readline 6.2
   - ncurses
  run:
   - readline 6.2
   - ncurses
