{% set name = "ape" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/fermi-lat/ape
  git_rev: standalone
build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}

  host:
    - cmake >=3.11
    - ncurses
    - readline

  run:
    - ncurses 
    - readline 
