{% set name = "ape" %}
{% set version = "2.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/fermi-lat/ape
  git_rev: standalone
build:
  number: 1

requirements:
  build:
    # - {{ compiler('c') }}

  host:
    - cmake >=3.11
    - ncurses >=6.1,<6.2
    - readline >=7.0,<8.0

  run:
    - ncurses >=6.1,<6.2
    - readline >=7.0,<8.0
